package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"meeseeks_box/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Function)
// DB Table: Plural (functions)
// Resource: Plural (Functions)
// Path: Plural (/functions)
// View Template Folder: Plural (/templates/functions/)

// FunctionsResource is the resource for the Function model
type FunctionsResource struct {
	buffalo.Resource
}

// List gets all Functions. This function is mapped to the path
// GET /functions
func (v FunctionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	functions := &models.Functions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Functions from the DB
	if err := q.All(functions); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("functions", functions)
		return c.Render(http.StatusOK, r.HTML("functions/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(functions))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(functions))
	}).Respond(c)
}

// Show gets the data for one Function. This function is mapped to
// the path GET /functions/{function_id}
func (v FunctionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Function
	function := &models.Function{}

	// To find the Function the parameter function_id is used.
	if err := tx.Find(function, c.Param("function_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("function", function)

		return c.Render(http.StatusOK, r.HTML("functions/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(function))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(function))
	}).Respond(c)
}

// New renders the form for creating a new Function.
// This function is mapped to the path GET /functions/new
func (v FunctionsResource) New(c buffalo.Context) error {
	c.Set("function", &models.Function{})

	return c.Render(http.StatusOK, r.HTML("functions/new.plush.html"))
}

// Create adds a Function to the DB. This function is mapped to the
// path POST /functions
func (v FunctionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Function
	function := &models.Function{}

	// Bind function to the html form elements
	if err := c.Bind(function); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(function)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("function", function)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("functions/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "function.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/functions/%v", function.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(function))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(function))
	}).Respond(c)
}

// Edit renders a edit form for a Function. This function is
// mapped to the path GET /functions/{function_id}/edit
func (v FunctionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Function
	function := &models.Function{}

	if err := tx.Find(function, c.Param("function_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("function", function)
	return c.Render(http.StatusOK, r.HTML("functions/edit.plush.html"))
}

// Update changes a Function in the DB. This function is mapped to
// the path PUT /functions/{function_id}
func (v FunctionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Function
	function := &models.Function{}

	if err := tx.Find(function, c.Param("function_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Function to the html form elements
	if err := c.Bind(function); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(function)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("function", function)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("functions/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "function.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/functions/%v", function.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(function))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(function))
	}).Respond(c)
}

// Destroy deletes a Function from the DB. This function is mapped
// to the path DELETE /functions/{function_id}
func (v FunctionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Function
	function := &models.Function{}

	// To find the Function the parameter function_id is used.
	if err := tx.Find(function, c.Param("function_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(function); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "function.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/functions")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(function))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(function))
	}).Respond(c)
}
