# Contains the configuration for deploying the meeseeks box application on the cluster. It will create the required
# Pods and Services. It will also define the secrets required for interacting back to the cluster.

# Deployments
# Define the Deployment / Service for mongo. Deployments will create a replicaset and pods according to the given
# configuration. You can deploy the following by running 'kubectl apply -f ./mongo.yml'. The service provides the "DNS"
# configuration for linking other Pods to the Mongo Service. Please be aware that selectors are really important for the
# service to link correctly to the Deployment (and the created Pods). It also means that unlike the Docker-Compose
# examples it is possible to have multiple different Pods use the same Service.
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clamber
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clamber
            image: clamber
          restartPolicy: OnFailure

---
# Services
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongo


---
# Secrets