# Contains the configuration for deploying the meeseeks box application on the cluster. It will create the required
# Pods and Services. It will also define the secrets required for interacting back to the cluster.
---
# Deployments

---
# Services

---
# Secrets