---
development:
  dialect: "sqlite3"
  database: C:\Users\Steven Carter\Projects\meeseeks_box\meeseeks_meeseeks_development.sqlite

test:
  dialect: "sqlite3"
  database: C:\Users\Steven Carter\Projects\meeseeks_box\meeseeks_meeseeks_test.sqlite

production:
  dialect: "sqlite3"
  database: C:\Users\Steven Carter\Projects\meeseeks_box\meeseeks_meeseeks_production.sqlite
