apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ name }}  
spec:
  replicas: 1
  template:
    metadata:
      name: {{ name }}
      labels:
        name: {{ name }}
    spec:
      containers:
      - image: {{ name }}:{{ version }}
        imagePullPolicy: Always
        name: {{ name }}               